// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hiqttetpjmjdxoixsqmb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpcXR0ZXRwam1qZHhvaXhzcW1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MDYyMDAsImV4cCI6MjA2NDA4MjIwMH0.A3cq51nvJw_spbZBECiSYn77v9lIWx_chmH7ldvasvI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);